apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: financetracker-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: your-secret-store
    kind: SecretStore
  target:
    name: financetracker-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: financetracker/JWT_ACCESS_SECRET
    - secretKey: CSRF_SECRET
      remoteRef:
        key: financetracker/CSRF_SECRET
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: financetracker/ENCRYPTION_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: financetracker/DB_PASSWORD